In [2]:
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
img1 = Image.open("0cdf5b5d0ce1_01_mask.gif")
img1 = np.array(img1)
print(img1)
img1 = Image.open("0cdf5b5d0ce1_01.jpg")
img1 = np.array(img1)
# print(img1)
print(img1.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(1280, 1918, 3)
